# cowsay
# Autogenerated from man page /usr/local/share/man/man1/cowsay.1
complete -c cowsay -s b -d 'Invokes Borg mode'
complete -c cowsay -s d -d 'Causes the cow to appear dead'
complete -c cowsay -s g -d 'Invokes greedy mode'
complete -c cowsay -s p -d 'Causes a state of paranoia to come over the cow'
complete -c cowsay -s s -d 'Makes the cow appear thoroughly stoned'
complete -c cowsay -s t -d 'Yields a tired cow'
complete -c cowsay -s w -d 'Is somewhat the opposite of -t, and initiates wired mode'
complete -c cowsay -s y -d 'Brings on the cow\'s youthful appearance'
complete -c cowsay -s e -d 'Selects the appearance of the cow\'s eyes, in which case the first two charact…'
complete -c cowsay -s f -d 'Specifies a particular cow picture file (cowfile) to use'
complete -c cowsay -s r -d 'Chooses a random cow from the cows on the COWPATH'
complete -c cowsay -s C -d 'Enables true-color (24-bit) cows'
complete -c cowsay -s l -d 'Lists the defined cows on the current COWPATH'
complete -c cowsay -s h -d 'Displays a help screen'
complete -c cowsay -s T -d 'and tongue_string; it must be two characters and does not appear by default'

