# kubeadm-init-phase-kubelet-start
# Autogenerated from man page /usr/local/share/man/man1/kubeadm-init-phase-kubelet-start.1
complete -c kubeadm-init-phase-kubelet-start -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-init-phase-kubelet-start -l cri-socket -d '	Path to the CRI socket to connect'
complete -c kubeadm-init-phase-kubelet-start -l dry-run -d '	Don\'t apply any changes; just output what would be done'
complete -c kubeadm-init-phase-kubelet-start -l node-name -d '	Specify the node name'
complete -c kubeadm-init-phase-kubelet-start -l patches -d '	Path to a directory that contains files named "target[suffix][+patchtype]'
complete -c kubeadm-init-phase-kubelet-start -l azure-container-registry-config -d '	Path to the file containing Azure container registry configuration informati…'
complete -c kubeadm-init-phase-kubelet-start -l rootfs -d '	[EXPERIMENTAL] The path to the \'real\' host root filesystem'
complete -c kubeadm-init-phase-kubelet-start -l version -d '	Print version information and quit EXAMPLE   # Writes a dynamic environment …'

