# kubeadm-join-phase-control-plane-prepare
# Autogenerated from man page /usr/local/share/man/man1/kubeadm-join-phase-control-plane-prepare.1
complete -c kubeadm-join-phase-control-plane-prepare -l azure-container-registry-config -d '	Path to the file containing Azure container registry configuration informati…'
complete -c kubeadm-join-phase-control-plane-prepare -l rootfs -d '	[EXPERIMENTAL] The path to the \'real\' host root filesystem'
complete -c kubeadm-join-phase-control-plane-prepare -l version -d '	Print version information and quit EXAMPLE   # Prepares the machine for serv…'

