# kubeadm-join-phase-control-plane-join-mark-control-plane
# Autogenerated from man page /usr/local/share/man/man1/kubeadm-join-phase-control-plane-join-mark-control-plane.1
complete -c kubeadm-join-phase-control-plane-join-mark-control-plane -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-join-phase-control-plane-join-mark-control-plane -l control-plane -d '	Create a new control plane instance on this node'
complete -c kubeadm-join-phase-control-plane-join-mark-control-plane -l dry-run -d '	Don\'t apply any changes; just output what would be done'
complete -c kubeadm-join-phase-control-plane-join-mark-control-plane -l node-name -d '	Specify the node name.  OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c kubeadm-join-phase-control-plane-join-mark-control-plane -l azure-container-registry-config -d '	Path to the file containing Azure container registry configuration informati…'
complete -c kubeadm-join-phase-control-plane-join-mark-control-plane -l rootfs -d '	[EXPERIMENTAL] The path to the \'real\' host root filesystem'
complete -c kubeadm-join-phase-control-plane-join-mark-control-plane -l version -d '	Print version information and quit SEE ALSO'

