# kubeadm-upgrade-node-phase-kubelet-config
# Autogenerated from man page /usr/local/share/man/man1/kubeadm-upgrade-node-phase-kubelet-config.1
complete -c kubeadm-upgrade-node-phase-kubelet-config -l dry-run -d '	Do not change any state, just output the actions that would be performed'
complete -c kubeadm-upgrade-node-phase-kubelet-config -l kubeconfig -d '	The kubeconfig file to use when talking to the cluster'
complete -c kubeadm-upgrade-node-phase-kubelet-config -l patches -d '	Path to a directory that contains files named "target[suffix][+patchtype]'
complete -c kubeadm-upgrade-node-phase-kubelet-config -l azure-container-registry-config -d '	Path to the file containing Azure container registry configuration informati…'
complete -c kubeadm-upgrade-node-phase-kubelet-config -l rootfs -d '	[EXPERIMENTAL] The path to the \'real\' host root filesystem'
complete -c kubeadm-upgrade-node-phase-kubelet-config -l version -d '	Print version information and quit SEE ALSO'

