# kubeadm-init-phase-bootstrap-token
# Autogenerated from man page /usr/local/share/man/man1/kubeadm-init-phase-bootstrap-token.1
complete -c kubeadm-init-phase-bootstrap-token -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-init-phase-bootstrap-token -l dry-run -d '	Don\'t apply any changes; just output what would be done'
complete -c kubeadm-init-phase-bootstrap-token -l kubeconfig -d '	The kubeconfig file to use when talking to the cluster'
complete -c kubeadm-init-phase-bootstrap-token -l skip-token-print -d '	Skip printing of the default bootstrap token generated by \'kubeadm init\''
complete -c kubeadm-init-phase-bootstrap-token -l azure-container-registry-config -d '	Path to the file containing Azure container registry configuration informati…'
complete -c kubeadm-init-phase-bootstrap-token -l rootfs -d '	[EXPERIMENTAL] The path to the \'real\' host root filesystem'
complete -c kubeadm-init-phase-bootstrap-token -l version -d '	Print version information and quit EXAMPLE   # Make all the bootstrap token …'

