# kubeadm-upgrade-node
# Autogenerated from man page /usr/local/share/man/man1/kubeadm-upgrade-node.1
complete -c kubeadm-upgrade-node -l certificate-renewal -d '	Perform the renewal of certificates used by component changed during upgrades'
complete -c kubeadm-upgrade-node -l dry-run -d '	Do not change any state, just output the actions that would be performed'
complete -c kubeadm-upgrade-node -l etcd-upgrade -d '	Perform the upgrade of etcd'
complete -c kubeadm-upgrade-node -l ignore-preflight-errors -d '	A list of checks whose errors will be shown as warnings'
complete -c kubeadm-upgrade-node -l kubeconfig -d '	The kubeconfig file to use when talking to the cluster'
complete -c kubeadm-upgrade-node -l patches -d '	Path to a directory that contains files named "target[suffix][+patchtype]'
complete -c kubeadm-upgrade-node -l skip-phases -d '	List of phases to be skipped OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c kubeadm-upgrade-node -l azure-container-registry-config -d '	Path to the file containing Azure container registry configuration informati…'
complete -c kubeadm-upgrade-node -l rootfs -d '	[EXPERIMENTAL] The path to the \'real\' host root filesystem'
complete -c kubeadm-upgrade-node -l version -d '	Print version information and quit SEE ALSO'

