# kubeadm-certs-check-expiration
# Autogenerated from man page /usr/local/share/man/man1/kubeadm-certs-check-expiration.1
complete -c kubeadm-certs-check-expiration -l cert-dir -d '	The path where to save the certificates'
complete -c kubeadm-certs-check-expiration -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-certs-check-expiration -l kubeconfig -d '	The kubeconfig file to use when talking to the cluster'
complete -c kubeadm-certs-check-expiration -l azure-container-registry-config -d '	Path to the file containing Azure container registry configuration informati…'
complete -c kubeadm-certs-check-expiration -l rootfs -d '	[EXPERIMENTAL] The path to the \'real\' host root filesystem'
complete -c kubeadm-certs-check-expiration -l version -d '	Print version information and quit SEE ALSO'

