# kubeadm-init-phase-etcd
# Autogenerated from man page /usr/local/share/man/man1/kubeadm-init-phase-etcd.1
complete -c kubeadm-init-phase-etcd -l azure-container-registry-config -d '	Path to the file containing Azure container registry configuration informati…'
complete -c kubeadm-init-phase-etcd -l rootfs -d '	[EXPERIMENTAL] The path to the \'real\' host root filesystem'
complete -c kubeadm-init-phase-etcd -l version -d '	Print version information and quit SEE ALSO'

