# kubeadm-certs-certificate-key
# Autogenerated from man page /usr/local/share/man/man1/kubeadm-certs-certificate-key.1
complete -c kubeadm-certs-certificate-key -l azure-container-registry-config -d '	Path to the file containing Azure container registry configuration informati…'
complete -c kubeadm-certs-certificate-key -l rootfs -d '	[EXPERIMENTAL] The path to the \'real\' host root filesystem'
complete -c kubeadm-certs-certificate-key -l version -d '	Print version information and quit SEE ALSO'

