# kubeadm-kubeconfig-user
# Autogenerated from man page /usr/local/share/man/man1/kubeadm-kubeconfig-user.1
complete -c kubeadm-kubeconfig-user -l client-name -d '	The name of user'
complete -c kubeadm-kubeconfig-user -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-kubeconfig-user -l org -d '	The organizations of the client certificate'
complete -c kubeadm-kubeconfig-user -l token -d '	The token that should be used as the authentication mechanism for this kubec…'
complete -c kubeadm-kubeconfig-user -l validity-period -d '	The validity period of the client certificate'
complete -c kubeadm-kubeconfig-user -l azure-container-registry-config -d '	Path to the file containing Azure container registry configuration informati…'
complete -c kubeadm-kubeconfig-user -l rootfs -d '	[EXPERIMENTAL] The path to the \'real\' host root filesystem'
complete -c kubeadm-kubeconfig-user -l version -d '	Print version information and quit EXAMPLE   # Output a kubeconfig file for …'

