# kubeadm-upgrade-diff
# Autogenerated from man page /usr/local/share/man/man1/kubeadm-upgrade-diff.1
complete -c kubeadm-upgrade-diff -l api-server-manifest -d '	path to API server manifest'
complete -c kubeadm-upgrade-diff -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-upgrade-diff -s c -l context-lines -d '	How many lines of context in the diff'
complete -c kubeadm-upgrade-diff -l controller-manager-manifest -d '	path to controller manifest'
complete -c kubeadm-upgrade-diff -l kubeconfig -d '	The kubeconfig file to use when talking to the cluster'
complete -c kubeadm-upgrade-diff -l scheduler-manifest -d '	path to scheduler manifest OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c kubeadm-upgrade-diff -l azure-container-registry-config -d '	Path to the file containing Azure container registry configuration informati…'
complete -c kubeadm-upgrade-diff -l rootfs -d '	[EXPERIMENTAL] The path to the \'real\' host root filesystem'
complete -c kubeadm-upgrade-diff -l version -d '	Print version information and quit SEE ALSO'

