# kubeadm-reset-phase
# Autogenerated from man page /usr/local/share/man/man1/kubeadm-reset-phase.1
complete -c kubeadm-reset-phase -l azure-container-registry-config -d '	Path to the file containing Azure container registry configuration informati…'
complete -c kubeadm-reset-phase -l rootfs -d '	[EXPERIMENTAL] The path to the \'real\' host root filesystem'
complete -c kubeadm-reset-phase -l version -d '	Print version information and quit SEE ALSO'

