# kubeadm-init-phase-certs-apiserver-kubelet-client
# Autogenerated from man page /usr/local/share/man/man1/kubeadm-init-phase-certs-apiserver-kubelet-client.1
complete -c kubeadm-init-phase-certs-apiserver-kubelet-client -l cert-dir -d '	The path where to save and store the certificates'
complete -c kubeadm-init-phase-certs-apiserver-kubelet-client -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-init-phase-certs-apiserver-kubelet-client -l dry-run -d '	Don\'t apply any changes; just output what would be done'
complete -c kubeadm-init-phase-certs-apiserver-kubelet-client -l kubernetes-version -d '	Choose a specific Kubernetes version for the control plane'
complete -c kubeadm-init-phase-certs-apiserver-kubelet-client -l azure-container-registry-config -d '	Path to the file containing Azure container registry configuration informati…'
complete -c kubeadm-init-phase-certs-apiserver-kubelet-client -l rootfs -d '	[EXPERIMENTAL] The path to the \'real\' host root filesystem'
complete -c kubeadm-init-phase-certs-apiserver-kubelet-client -l version -d '	Print version information and quit SEE ALSO'

