# kubeadm-upgrade-plan
# Autogenerated from man page /usr/local/share/man/man1/kubeadm-upgrade-plan.1
complete -c kubeadm-upgrade-plan -l allow-experimental-upgrades -d '	Show unstable versions of Kubernetes as an upgrade alternative and allow upg…'
complete -c kubeadm-upgrade-plan -l allow-release-candidate-upgrades -d '	Show release candidate versions of Kubernetes as an upgrade alternative and …'
complete -c kubeadm-upgrade-plan -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-upgrade-plan -l feature-gates -d '	A set of key=value pairs that describe feature gates for various features'
complete -c kubeadm-upgrade-plan -l ignore-preflight-errors -d '	A list of checks whose errors will be shown as warnings'
complete -c kubeadm-upgrade-plan -l kubeconfig -d '	The kubeconfig file to use when talking to the cluster'
complete -c kubeadm-upgrade-plan -s o -l output -d '	EXPERIMENTAL: Output format.  One of: text|json|yaml'
complete -c kubeadm-upgrade-plan -l print-config -d '	Specifies whether the configuration file that will be used in the upgrade sh…'
complete -c kubeadm-upgrade-plan -l show-managed-fields -d '	If true, keep the managedFields when printing objects in JSON or YAML format'
complete -c kubeadm-upgrade-plan -l azure-container-registry-config -d '	Path to the file containing Azure container registry configuration informati…'
complete -c kubeadm-upgrade-plan -l rootfs -d '	[EXPERIMENTAL] The path to the \'real\' host root filesystem'
complete -c kubeadm-upgrade-plan -l version -d '	Print version information and quit SEE ALSO'

