# kubeadm-join-phase-control-plane-join-update-status
# Autogenerated from man page /usr/local/share/man/man1/kubeadm-join-phase-control-plane-join-update-status.1
complete -c kubeadm-join-phase-control-plane-join-update-status -l apiserver-advertise-address -d '	If the node should host a new control plane instance, the IP address the API…'
complete -c kubeadm-join-phase-control-plane-join-update-status -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-join-phase-control-plane-join-update-status -l control-plane -d '	Create a new control plane instance on this node'
complete -c kubeadm-join-phase-control-plane-join-update-status -l node-name -d '	Specify the node name.  OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c kubeadm-join-phase-control-plane-join-update-status -l azure-container-registry-config -d '	Path to the file containing Azure container registry configuration informati…'
complete -c kubeadm-join-phase-control-plane-join-update-status -l rootfs -d '	[EXPERIMENTAL] The path to the \'real\' host root filesystem'
complete -c kubeadm-join-phase-control-plane-join-update-status -l version -d '	Print version information and quit SEE ALSO'

