# kubeadm-certs-renew
# Autogenerated from man page /usr/local/share/man/man1/kubeadm-certs-renew.1
complete -c kubeadm-certs-renew -l azure-container-registry-config -d '	Path to the file containing Azure container registry configuration informati…'
complete -c kubeadm-certs-renew -l rootfs -d '	[EXPERIMENTAL] The path to the \'real\' host root filesystem'
complete -c kubeadm-certs-renew -l version -d '	Print version information and quit SEE ALSO'

