# kubeadm-upgrade
# Autogenerated from man page /usr/local/share/man/man1/kubeadm-upgrade.1
complete -c kubeadm-upgrade -l azure-container-registry-config -d '	Path to the file containing Azure container registry configuration informati…'
complete -c kubeadm-upgrade -l rootfs -d '	[EXPERIMENTAL] The path to the \'real\' host root filesystem'
complete -c kubeadm-upgrade -l version -d '	Print version information and quit SEE ALSO'

