# kubeadm-version
# Autogenerated from man page /usr/local/share/man/man1/kubeadm-version.1
complete -c kubeadm-version -s o -l output -d '	Output format; available options are \'yaml\', \'json\' and \'short\' OPTIONS INHE…'
complete -c kubeadm-version -l azure-container-registry-config -d '	Path to the file containing Azure container registry configuration informati…'
complete -c kubeadm-version -l rootfs -d '	[EXPERIMENTAL] The path to the \'real\' host root filesystem'
complete -c kubeadm-version -l version -d '	Print version information and quit SEE ALSO'

