# kubeadm-config-print-init-defaults
# Autogenerated from man page /usr/local/share/man/man1/kubeadm-config-print-init-defaults.1
complete -c kubeadm-config-print-init-defaults -l component-configs -d '	A comma-separated list for component config API objects to print the default…'
complete -c kubeadm-config-print-init-defaults -l azure-container-registry-config -d '	Path to the file containing Azure container registry configuration informati…'
complete -c kubeadm-config-print-init-defaults -l kubeconfig -d '	The kubeconfig file to use when talking to the cluster'
complete -c kubeadm-config-print-init-defaults -l rootfs -d '	[EXPERIMENTAL] The path to the \'real\' host root filesystem'
complete -c kubeadm-config-print-init-defaults -l version -d '	Print version information and quit SEE ALSO'

