# kubeadm-init-phase-certs-all
# Autogenerated from man page /usr/local/share/man/man1/kubeadm-init-phase-certs-all.1
complete -c kubeadm-init-phase-certs-all -l apiserver-advertise-address -d '	The IP address the API Server will advertise it\'s listening on'
complete -c kubeadm-init-phase-certs-all -l apiserver-cert-extra-sans -d '	Optional extra Subject Alternative Names (SANs) to use for the API Server se…'
complete -c kubeadm-init-phase-certs-all -l cert-dir -d '	The path where to save and store the certificates'
complete -c kubeadm-init-phase-certs-all -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-init-phase-certs-all -l control-plane-endpoint -d '	Specify a stable IP address or DNS name for the control plane'
complete -c kubeadm-init-phase-certs-all -l dry-run -d '	Don\'t apply any changes; just output what would be done'
complete -c kubeadm-init-phase-certs-all -l kubernetes-version -d '	Choose a specific Kubernetes version for the control plane'
complete -c kubeadm-init-phase-certs-all -l service-cidr -d '	Use alternative range of IP address for service VIPs'
complete -c kubeadm-init-phase-certs-all -l service-dns-domain -d '	Use alternative domain for services, e. g.  "myorg. internal"'
complete -c kubeadm-init-phase-certs-all -l azure-container-registry-config -d '	Path to the file containing Azure container registry configuration informati…'
complete -c kubeadm-init-phase-certs-all -l rootfs -d '	[EXPERIMENTAL] The path to the \'real\' host root filesystem'
complete -c kubeadm-init-phase-certs-all -l version -d '	Print version information and quit SEE ALSO'

