# kubeadm-token
# Autogenerated from man page /usr/local/share/man/man1/kubeadm-token.1
complete -c kubeadm-token -l dry-run -d '	Whether to enable dry-run mode or not'
complete -c kubeadm-token -l kubeconfig -d '	The kubeconfig file to use when talking to the cluster'
complete -c kubeadm-token -l azure-container-registry-config -d '	Path to the file containing Azure container registry configuration informati…'
complete -c kubeadm-token -l rootfs -d '	[EXPERIMENTAL] The path to the \'real\' host root filesystem'
complete -c kubeadm-token -l version -d '	Print version information and quit SEE ALSO'

