# kubeadm-upgrade-node-phase-control-plane
# Autogenerated from man page /usr/local/share/man/man1/kubeadm-upgrade-node-phase-control-plane.1
complete -c kubeadm-upgrade-node-phase-control-plane -l certificate-renewal -d '	Perform the renewal of certificates used by component changed during upgrades'
complete -c kubeadm-upgrade-node-phase-control-plane -l dry-run -d '	Do not change any state, just output the actions that would be performed'
complete -c kubeadm-upgrade-node-phase-control-plane -l etcd-upgrade -d '	Perform the upgrade of etcd'
complete -c kubeadm-upgrade-node-phase-control-plane -l kubeconfig -d '	The kubeconfig file to use when talking to the cluster'
complete -c kubeadm-upgrade-node-phase-control-plane -l patches -d '	Path to a directory that contains files named "target[suffix][+patchtype]'
complete -c kubeadm-upgrade-node-phase-control-plane -l azure-container-registry-config -d '	Path to the file containing Azure container registry configuration informati…'
complete -c kubeadm-upgrade-node-phase-control-plane -l rootfs -d '	[EXPERIMENTAL] The path to the \'real\' host root filesystem'
complete -c kubeadm-upgrade-node-phase-control-plane -l version -d '	Print version information and quit SEE ALSO'

