# kubeadm-certs-generate-csr
# Autogenerated from man page /usr/local/share/man/man1/kubeadm-certs-generate-csr.1
complete -c kubeadm-certs-generate-csr -l cert-dir -d '	The path where to save the certificates'
complete -c kubeadm-certs-generate-csr -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-certs-generate-csr -l kubeconfig-dir -d '	The path where to save the kubeconfig file'
complete -c kubeadm-certs-generate-csr -l azure-container-registry-config -d '	Path to the file containing Azure container registry configuration informati…'
complete -c kubeadm-certs-generate-csr -l rootfs -d '	[EXPERIMENTAL] The path to the \'real\' host root filesystem'
complete -c kubeadm-certs-generate-csr -l version -d '	Print version information and quit EXAMPLE   # The following command will ge…'

