# kubelet
# Autogenerated from man page /usr/local/share/man/man1/kubelet.1
complete -c kubelet -l azure-container-registry-config -d '	Path to the file containing Azure container registry configuration informati…'
complete -c kubelet -l version -d '	Print version information and quit HISTORY'

