# kubeadm-init-phase-kubeconfig-scheduler
# Autogenerated from man page /usr/local/share/man/man1/kubeadm-init-phase-kubeconfig-scheduler.1
complete -c kubeadm-init-phase-kubeconfig-scheduler -l apiserver-advertise-address -d '	The IP address the API Server will advertise it\'s listening on'
complete -c kubeadm-init-phase-kubeconfig-scheduler -l apiserver-bind-port -d '	Port for the API Server to bind to'
complete -c kubeadm-init-phase-kubeconfig-scheduler -l cert-dir -d '	The path where to save and store the certificates'
complete -c kubeadm-init-phase-kubeconfig-scheduler -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-init-phase-kubeconfig-scheduler -l control-plane-endpoint -d '	Specify a stable IP address or DNS name for the control plane'
complete -c kubeadm-init-phase-kubeconfig-scheduler -l dry-run -d '	Don\'t apply any changes; just output what would be done'
complete -c kubeadm-init-phase-kubeconfig-scheduler -l kubeconfig-dir -d '	The path where to save the kubeconfig file'
complete -c kubeadm-init-phase-kubeconfig-scheduler -l kubernetes-version -d '	Choose a specific Kubernetes version for the control plane'
complete -c kubeadm-init-phase-kubeconfig-scheduler -l azure-container-registry-config -d '	Path to the file containing Azure container registry configuration informati…'
complete -c kubeadm-init-phase-kubeconfig-scheduler -l rootfs -d '	[EXPERIMENTAL] The path to the \'real\' host root filesystem'
complete -c kubeadm-init-phase-kubeconfig-scheduler -l version -d '	Print version information and quit SEE ALSO'

