# kubeadm-init-phase-kubelet-finalize-all
# Autogenerated from man page /usr/local/share/man/man1/kubeadm-init-phase-kubelet-finalize-all.1
complete -c kubeadm-init-phase-kubelet-finalize-all -l cert-dir -d '	The path where to save and store the certificates'
complete -c kubeadm-init-phase-kubelet-finalize-all -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-init-phase-kubelet-finalize-all -l dry-run -d '	Don\'t apply any changes; just output what would be done'
complete -c kubeadm-init-phase-kubelet-finalize-all -l azure-container-registry-config -d '	Path to the file containing Azure container registry configuration informati…'
complete -c kubeadm-init-phase-kubelet-finalize-all -l rootfs -d '	[EXPERIMENTAL] The path to the \'real\' host root filesystem'
complete -c kubeadm-init-phase-kubelet-finalize-all -l version -d '	Print version information and quit EXAMPLE   # Updates settings relevant to …'

