# kubeadm-init-phase-kubelet-finalize
# Autogenerated from man page /usr/local/share/man/man1/kubeadm-init-phase-kubelet-finalize.1
complete -c kubeadm-init-phase-kubelet-finalize -l azure-container-registry-config -d '	Path to the file containing Azure container registry configuration informati…'
complete -c kubeadm-init-phase-kubelet-finalize -l rootfs -d '	[EXPERIMENTAL] The path to the \'real\' host root filesystem'
complete -c kubeadm-init-phase-kubelet-finalize -l version -d '	Print version information and quit EXAMPLE   # Updates settings relevant to …'

