# kubeadm-init-phase-upload-config-kubelet
# Autogenerated from man page /usr/local/share/man/man1/kubeadm-init-phase-upload-config-kubelet.1
complete -c kubeadm-init-phase-upload-config-kubelet -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-init-phase-upload-config-kubelet -l dry-run -d '	Don\'t apply any changes; just output what would be done'
complete -c kubeadm-init-phase-upload-config-kubelet -l kubeconfig -d '	The kubeconfig file to use when talking to the cluster'
complete -c kubeadm-init-phase-upload-config-kubelet -l azure-container-registry-config -d '	Path to the file containing Azure container registry configuration informati…'
complete -c kubeadm-init-phase-upload-config-kubelet -l rootfs -d '	[EXPERIMENTAL] The path to the \'real\' host root filesystem'
complete -c kubeadm-init-phase-upload-config-kubelet -l version -d '	Print version information and quit EXAMPLE   # Upload the kubelet configurat…'

