# kubeadm-reset-phase-preflight
# Autogenerated from man page /usr/local/share/man/man1/kubeadm-reset-phase-preflight.1
complete -c kubeadm-reset-phase-preflight -l dry-run -d '	Don\'t apply any changes; just output what would be done'
complete -c kubeadm-reset-phase-preflight -s f -l force -d '	Reset the node without prompting for confirmation'
complete -c kubeadm-reset-phase-preflight -l ignore-preflight-errors -d '	A list of checks whose errors will be shown as warnings'
complete -c kubeadm-reset-phase-preflight -l azure-container-registry-config -d '	Path to the file containing Azure container registry configuration informati…'
complete -c kubeadm-reset-phase-preflight -l rootfs -d '	[EXPERIMENTAL] The path to the \'real\' host root filesystem'
complete -c kubeadm-reset-phase-preflight -l version -d '	Print version information and quit SEE ALSO'

