# kubeadm-init-phase-addon-coredns
# Autogenerated from man page /usr/local/share/man/man1/kubeadm-init-phase-addon-coredns.1
complete -c kubeadm-init-phase-addon-coredns -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-init-phase-addon-coredns -l dry-run -d '	Don\'t apply any changes; just output what would be done'
complete -c kubeadm-init-phase-addon-coredns -l feature-gates -d '	A set of key=value pairs that describe feature gates for various features'
complete -c kubeadm-init-phase-addon-coredns -l image-repository -d '	Choose a container registry to pull control plane images from'
complete -c kubeadm-init-phase-addon-coredns -l kubeconfig -d '	The kubeconfig file to use when talking to the cluster'
complete -c kubeadm-init-phase-addon-coredns -l kubernetes-version -d '	Choose a specific Kubernetes version for the control plane'
complete -c kubeadm-init-phase-addon-coredns -l print-manifest -d '	Print the addon manifests to STDOUT instead of installing them'
complete -c kubeadm-init-phase-addon-coredns -l service-cidr -d '	Use alternative range of IP address for service VIPs'
complete -c kubeadm-init-phase-addon-coredns -l service-dns-domain -d '	Use alternative domain for services, e. g.  "myorg. internal"'
complete -c kubeadm-init-phase-addon-coredns -l azure-container-registry-config -d '	Path to the file containing Azure container registry configuration informati…'
complete -c kubeadm-init-phase-addon-coredns -l rootfs -d '	[EXPERIMENTAL] The path to the \'real\' host root filesystem'
complete -c kubeadm-init-phase-addon-coredns -l version -d '	Print version information and quit SEE ALSO'

