# kubeadm-init-phase-etcd-local
# Autogenerated from man page /usr/local/share/man/man1/kubeadm-init-phase-etcd-local.1
complete -c kubeadm-init-phase-etcd-local -l cert-dir -d '	The path where to save and store the certificates'
complete -c kubeadm-init-phase-etcd-local -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-init-phase-etcd-local -l dry-run -d '	Don\'t apply any changes; just output what would be done'
complete -c kubeadm-init-phase-etcd-local -l image-repository -d '	Choose a container registry to pull control plane images from'
complete -c kubeadm-init-phase-etcd-local -l patches -d '	Path to a directory that contains files named "target[suffix][+patchtype]'
complete -c kubeadm-init-phase-etcd-local -l azure-container-registry-config -d '	Path to the file containing Azure container registry configuration informati…'
complete -c kubeadm-init-phase-etcd-local -l rootfs -d '	[EXPERIMENTAL] The path to the \'real\' host root filesystem'
complete -c kubeadm-init-phase-etcd-local -l version -d '	Print version information and quit EXAMPLE   # Generates the static Pod mani…'

