# kubeadm-init-phase-addon-kube-proxy
# Autogenerated from man page /usr/local/share/man/man1/kubeadm-init-phase-addon-kube-proxy.1
complete -c kubeadm-init-phase-addon-kube-proxy -l apiserver-advertise-address -d '	The IP address the API Server will advertise it\'s listening on'
complete -c kubeadm-init-phase-addon-kube-proxy -l apiserver-bind-port -d '	Port for the API Server to bind to'
complete -c kubeadm-init-phase-addon-kube-proxy -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-init-phase-addon-kube-proxy -l control-plane-endpoint -d '	Specify a stable IP address or DNS name for the control plane'
complete -c kubeadm-init-phase-addon-kube-proxy -l dry-run -d '	Don\'t apply any changes; just output what would be done'
complete -c kubeadm-init-phase-addon-kube-proxy -l image-repository -d '	Choose a container registry to pull control plane images from'
complete -c kubeadm-init-phase-addon-kube-proxy -l kubeconfig -d '	The kubeconfig file to use when talking to the cluster'
complete -c kubeadm-init-phase-addon-kube-proxy -l kubernetes-version -d '	Choose a specific Kubernetes version for the control plane'
complete -c kubeadm-init-phase-addon-kube-proxy -l pod-network-cidr -d '	Specify range of IP addresses for the pod network'
complete -c kubeadm-init-phase-addon-kube-proxy -l print-manifest -d '	Print the addon manifests to STDOUT instead of installing them OPTIONS INHER…'
complete -c kubeadm-init-phase-addon-kube-proxy -l azure-container-registry-config -d '	Path to the file containing Azure container registry configuration informati…'
complete -c kubeadm-init-phase-addon-kube-proxy -l rootfs -d '	[EXPERIMENTAL] The path to the \'real\' host root filesystem'
complete -c kubeadm-init-phase-addon-kube-proxy -l version -d '	Print version information and quit SEE ALSO'

