# kubeadm-completion
# Autogenerated from man page /usr/local/share/man/man1/kubeadm-completion.1
complete -c kubeadm-completion -l azure-container-registry-config -d '	Path to the file containing Azure container registry configuration informati…'
complete -c kubeadm-completion -l rootfs -d '	[EXPERIMENTAL] The path to the \'real\' host root filesystem'
complete -c kubeadm-completion -l version -d '	Print version information and quit EXAMPLE # Install bash completion on a Ma…'

