# kubeadm-init-phase-show-join-command
# Autogenerated from man page /usr/local/share/man/man1/kubeadm-init-phase-show-join-command.1
complete -c kubeadm-init-phase-show-join-command -l azure-container-registry-config -d '	Path to the file containing Azure container registry configuration informati…'
complete -c kubeadm-init-phase-show-join-command -l rootfs -d '	[EXPERIMENTAL] The path to the \'real\' host root filesystem'
complete -c kubeadm-init-phase-show-join-command -l version -d '	Print version information and quit SEE ALSO'

