# kubeadm-join-phase-control-plane-join
# Autogenerated from man page /usr/local/share/man/man1/kubeadm-join-phase-control-plane-join.1
complete -c kubeadm-join-phase-control-plane-join -l azure-container-registry-config -d '	Path to the file containing Azure container registry configuration informati…'
complete -c kubeadm-join-phase-control-plane-join -l rootfs -d '	[EXPERIMENTAL] The path to the \'real\' host root filesystem'
complete -c kubeadm-join-phase-control-plane-join -l version -d '	Print version information and quit EXAMPLE   # Joins a machine as a control …'

