# kubeadm-init-phase-preflight
# Autogenerated from man page /usr/local/share/man/man1/kubeadm-init-phase-preflight.1
complete -c kubeadm-init-phase-preflight -l config -d '	Path to a kubeadm configuration file'
complete -c kubeadm-init-phase-preflight -l dry-run -d '	Don\'t apply any changes; just output what would be done'
complete -c kubeadm-init-phase-preflight -l ignore-preflight-errors -d '	A list of checks whose errors will be shown as warnings'
complete -c kubeadm-init-phase-preflight -l azure-container-registry-config -d '	Path to the file containing Azure container registry configuration informati…'
complete -c kubeadm-init-phase-preflight -l rootfs -d '	[EXPERIMENTAL] The path to the \'real\' host root filesystem'
complete -c kubeadm-init-phase-preflight -l version -d '	Print version information and quit EXAMPLE   # Run pre-flight checks for kub…'

