# kubeadm-token-list
# Autogenerated from man page /usr/local/share/man/man1/kubeadm-token-list.1
complete -c kubeadm-token-list -l allow-missing-template-keys -d '	If true, ignore any errors in templates when a field or map key is missing i…'
complete -c kubeadm-token-list -s o -l experimental-output -d '	Output format'
complete -c kubeadm-token-list -l show-managed-fields -d '	If true, keep the managedFields when printing objects in JSON or YAML format'
complete -c kubeadm-token-list -l azure-container-registry-config -d '	Path to the file containing Azure container registry configuration informati…'
complete -c kubeadm-token-list -l dry-run -d '	Whether to enable dry-run mode or not'
complete -c kubeadm-token-list -l kubeconfig -d '	The kubeconfig file to use when talking to the cluster'
complete -c kubeadm-token-list -l rootfs -d '	[EXPERIMENTAL] The path to the \'real\' host root filesystem'
complete -c kubeadm-token-list -l version -d '	Print version information and quit SEE ALSO'

