# kubeadm-upgrade-node-phase-preflight
# Autogenerated from man page /usr/local/share/man/man1/kubeadm-upgrade-node-phase-preflight.1
complete -c kubeadm-upgrade-node-phase-preflight -l ignore-preflight-errors -d '	A list of checks whose errors will be shown as warnings'
complete -c kubeadm-upgrade-node-phase-preflight -l azure-container-registry-config -d '	Path to the file containing Azure container registry configuration informati…'
complete -c kubeadm-upgrade-node-phase-preflight -l rootfs -d '	[EXPERIMENTAL] The path to the \'real\' host root filesystem'
complete -c kubeadm-upgrade-node-phase-preflight -l version -d '	Print version information and quit SEE ALSO'

