# kubeadm-config-print
# Autogenerated from man page /usr/local/share/man/man1/kubeadm-config-print.1
complete -c kubeadm-config-print -l azure-container-registry-config -d '	Path to the file containing Azure container registry configuration informati…'
complete -c kubeadm-config-print -l kubeconfig -d '	The kubeconfig file to use when talking to the cluster'
complete -c kubeadm-config-print -l rootfs -d '	[EXPERIMENTAL] The path to the \'real\' host root filesystem'
complete -c kubeadm-config-print -l version -d '	Print version information and quit SEE ALSO'

