# networkQuality
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/networkQuality.8
complete -c networkQuality -s C -d 'Use custom configuration URL or path (with scheme file://)'
complete -c networkQuality -s I -d 'Bind test to interface (e. g. , en0, pdp_ip0,'
complete -c networkQuality -s r -d 'Connect to host or IP, overriding DNS for initial config request'
complete -c networkQuality -s c -d 'Produce computer-readable output'
complete -c networkQuality -s h -d 'Show help'
complete -c networkQuality -s k -d 'Disable verification of the server identity via TLS'
complete -c networkQuality -s p -d 'Use iCloud Private Relay'
complete -c networkQuality -s s -d 'Run tests sequentially instead of parallel upload/download'
complete -c networkQuality -s v -d 'Verbose output'

